version: '3'
networks:
  caddy:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  
services:

  mongo:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - ./data-db:/data/db
    networks:
      - caddy


  parse:
    container_name: parseserver
    image: parseplatform/parse-server
    ports:
        - 1337:1337
    links:
        - mongo
    environment:
        - PARSE_SERVER_APPLICATION_ID=yourappid
        - PARSE_SERVER_MASTER_KEY=yourmasterkey
        - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/dev
    command:
        - --masterKeyIps=10.5.0.5
        - --masterKeyIps=10.5.0.3
    networks:      
      - caddy
    labels:
      caddy: server.aptley.in
      caddy.reverse_proxy: "{{upstreams 1337}}"

  dashboard:
    container_name: parsedashboard
    image: parseplatform/parse-dashboard
    ports:
      - 4040:4040
    environment:
      - PARSE_DASHBOARD_SERVER_URL=https://server.aptley.in/parse
      - PARSE_DASHBOARD_APP_ID=yourappid
      - PARSE_DASHBOARD_MASTER_KEY=yourmasterkey
      - PARSE_DASHBOARD_APP_NAME=MyApp
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_USER_ID=user
      - PARSE_DASHBOARD_USER_PASSWORD=pass
      - PARSE_SERVER_APPLICATION_ID=yourappid
      - PARSE_SERVER_MASTER_KEY=yourmasterkey
    networks:
      caddy:
        ipv4_address: 10.5.0.5
    labels:
      caddy: dashboard.aptley.in
      caddy.reverse_proxy: "{{upstreams 4040}}"
  

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/containers/caddy/site:/srv
      - /home/ubuntu/containers/caddy/caddy_data:/data
      - /home/ubuntu/containers/caddy/caddy_config:/config
    networks:
      caddy:
        ipv4_address: 10.5.0.3

volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local

