version: '2'
networks:
  caddy:
services:

  mongo:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - ./data-db:/data/db
    networks:
      - caddy


  parse:
    container_name: parseserver
    image: parseplatform/parse-server
    ports:
        - 1337:1337
    links:
        - mongo
    environment:
        - PARSE_SERVER_APPLICATION_ID=yourappid
        - PARSE_SERVER_MASTER_KEY=yourmasterkey
        - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/dev
        - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
        - PARSE_SERVER_LIVE_QUERY={"classNames":["people","monitor"]}
    networks:
      - caddy
    labels:
      caddy: server.aptley.in
      caddy.reverse_proxy: "{{upstreams 1337}}"

  dashboard:
    container_name: parsedashboard
    image: parseplatform/parse-dashboard
    ports:
      - 4040:4040
    environment:
      - PARSE_DASHBOARD_SERVER_URL=https://server.aptley.in/parse/classes
      - PARSE_DASHBOARD_APP_ID=yourappid
      - PARSE_DASHBOARD_MASTER_KEY=yourmasterkey
      - PARSE_DASHBOARD_APP_NAME=MyApp
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_USER_ID=user
      - PARSE_DASHBOARD_USER_PASSWORD=pass
      - PARSE_SERVER_APPLICATION_ID=yourappid
      - PARSE_SERVER_MASTER_KEY=yourmasterkey              
    networks:
      - caddy
    labels:
      caddy: dashboard.aptley.in
      caddy.reverse_proxy: "{{upstreams 4040}}"     
      

  # parse-dashboard:
  #   container_name: parsedashboard
  #   image: docker.io/bitnami/parse-dashboard:5
  #   ports:
  #     - '4040:4040'
  #   volumes:
  #     - 'parse_dashboard_data:/bitnami'
  #   depends_on:
  #     - parse
  #   environment:
  #     - PARSE_DASHBOARD_PARSE_HOST=server.aptley.in
  #     - PARSE_DASHBOARD_PARSE_PORT_NUMBER=80
  #     - PARSE_DASHBOARD_PARSE_MOUNT_PATH=/parse/classes
  #     - PARSE_DASHBOARD_PARSE_APP_ID=myappID
  #     - PARSE_DASHBOARD_PARSE_MASTER_KEY=mymasterKey
  #   networks:
  #     - caddy
  #   labels:
  #     caddy: dashboard.aptley.in
  #     caddy.reverse_proxy: "{{upstreams 4040}}"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/containers/caddy/site:/srv
      - /home/ubuntu/containers/caddy/caddy_data:/data
      - /home/ubuntu/containers/caddy/caddy_config:/config
    networks:
      - caddy

volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
