version: '2'
networks:
  caddy:
services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=bn_parse
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=bitnami123
    networks:
      - caddy

  parse:
    container_name: parseserver
    image: docker.io/bitnami/parse:5
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami/parse'
    depends_on:
      - mongodb
    environment:
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=bn_parse
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=bitnami123
      - PARSE_ENABLE_HTTPS=yes
      - PARSE_MOUNT_PATH=/parse
    networks:
        - caddy
    labels:
      caddy: server.aptley.in
      caddy.reverse_proxy: "{{upstreams 1337}}"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/containers/caddy/site:/srv
      - /home/ubuntu/containers/caddy/caddy_data:/data
      - /home/ubuntu/containers/caddy/caddy_config:/config
    networks:
      - caddy
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
