version: '2'
services:
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:5
    ports:
      - '9000:9000'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:
      - PARSE_DASHBOARD_ENABLE_HTTPS: yes
      - PARSE_DASHBOARD_EXTERNAL_HTTP_PORT_NUMBER: 9000
      - PARSE_DASHBOARD_EXTERNAL_HTTPS_PORT_NUMBER: 9000
      - PARSE_DASHBOARD_PARSE_HOST: server.aptley.in
      - PARSE_DASHBOARD_PORT_NUMBER: 9000
      - PARSE_DASHBOARD_PARSE_PORT_NUMBER: 1337
      - PARSE_DASHBOARD_PARSE_APP_ID: myappID
      - PARSE_DASHBOARD_PARSE_APP_NAME: myappID
      - PARSE_DASHBOARD_PARSE_MASTER_KEY: mymasterKey
      - PARSE_DASHBOARD_PARSE_MOUNT_PATH: /parse
      - PARSE_DASHBOARD_PARSE_PROTOCOL: https
      - PARSE_DASHBOARD_USERNAME: user
      - PARSE_DASHBOARD_PASSWORD: bitnami

volumes:
  parse_dashboard_data:
    driver: local
