version: "3"
services:  
  mysql:
    image: {{ DOCKER_IMAGE_MYSQL }}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    user: "999:999"
    privileged: false
    volumes:
      - ../../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
  mysql-permissions:
    image: {{ DOCKER_IMAGE_PERMISSIONS }}
    command: ["999", "/var/lib/mysql"]
    restart: on-failure
    volumes:
      - ../../data/mysql:/var/lib/mysql  

  lms:
    image: {{ DOCKER_IMAGE_OPENEDX }}
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
      UWSGI_WORKERS: {{ OPENEDX_LMS_UWSGI_WORKERS }}
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ../apps/openedx/config:/openedx/config:ro
      - ../apps/openedx/uwsgi.ini:/openedx/edx-platform/uwsgi.ini:ro
      - ../../data/lms:/openedx/data
      - ../../data/openedx-media:/openedx/media
    depends_on:
      - lms-permissions
      {% if RUN_MYSQL %}- mysql{% endif %}
      {% if RUN_ELASTICSEARCH %}- elasticsearch{% endif %}
      {% if RUN_MONGODB %}- mongodb{% endif %}
      {% if RUN_REDIS %}- redis{% endif %}
      {% if RUN_SMTP %}- smtp{% endif %}
      {{ patch("local-docker-compose-lms-dependencies")|indent(6) }}
  lms-permissions:
    image: {{ DOCKER_IMAGE_PERMISSIONS }}
    command: ["1000", "/openedx/data", "/openedx/media"]
    restart: on-failure
    volumes:
      - ../../data/lms:/openedx/data
      - ../../data/openedx-media:/openedx/media 

  cms:
    image: {{ DOCKER_IMAGE_OPENEDX }}
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
      UWSGI_WORKERS: {{ OPENEDX_CMS_UWSGI_WORKERS }}
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ../apps/openedx/config:/openedx/config:ro
      - ../apps/openedx/uwsgi.ini:/openedx/edx-platform/uwsgi.ini:ro
      - ../../data/cms:/openedx/data
      - ../../data/openedx-media:/openedx/media
    depends_on:
      - cms-permissions
      {% if RUN_MYSQL %}- mysql{% endif %}
      {% if RUN_ELASTICSEARCH %}- elasticsearch{% endif %}
      {% if RUN_MONGODB %}- mongodb{% endif %}
      {% if RUN_REDIS %}- redis{% endif %}
      {% if RUN_SMTP %}- smtp{% endif %}
      {% if RUN_LMS %}- lms{% endif %}
      {{ patch("local-docker-compose-cms-dependencies")|indent(6) }}
  cms-permissions:
    image: {{ DOCKER_IMAGE_PERMISSIONS }}
    command: ["1000", "/openedx/data", "/openedx/media"]
    restart: on-failure
    volumes:
      - ../../data/cms:/openedx/data
      - ../../data/openedx-media:/openedx/media